import { readFile } from "node:fs/promises";
import path from "node:path";

const DEFAULT_ECOSYSTEM_BASE_URL = "https://ekosistem.javavolcano-touroperator.com";
const REVALIDATE_SECONDS = 60;

type EcosystemSchemaPayload = {
  route: string;
  payload?: {
    route?: string;
    json_ld?: {
      "@context"?: string;
      "@graph"?: unknown[];
    };
  };
};

type SchemaNode = Record<string, any>;

function ecosystemBaseUrl() {
  return (
    process.env.JVTO_ECOSYSTEM_BASE_URL ||
    process.env.NEXT_PUBLIC_ECOSYSTEM_BASE_URL ||
    DEFAULT_ECOSYSTEM_BASE_URL
  ).replace(/\/+$/, "");
}

function nodeTypes(node: SchemaNode): string[] {
  const type = node["@type"];
  if (Array.isArray(type)) return type.filter((item): item is string => typeof item === "string");
  return typeof type === "string" ? [type] : [];
}

function isJsonResponse(response: Response) {
  return response.headers.get("content-type")?.includes("application/json") ?? false;
}

export async function getEcosystemPageSchema(route: string) {
  const url = `${ecosystemBaseUrl()}/api/schema/page?route=${encodeURIComponent(route)}`;

  try {
    const response = await fetch(url, {
      headers: { accept: "application/json" },
      next: { revalidate: REVALIDATE_SECONDS, tags: ["ecosystem-schema"] },
    });
    if (!response.ok) return null;
    if (!isJsonResponse(response)) return null;

    const data = (await response.json()) as EcosystemSchemaPayload;
    const graph = data.payload?.json_ld;
    if (!graph || !Array.isArray(graph["@graph"])) return null;
    return graph as { "@context"?: string; "@graph": SchemaNode[] };
  } catch (error) {
    console.error(
      `[ecosystemContent] Failed to fetch schema for ${route}: ${error instanceof Error ? error.message : String(error)}`,
    );
    return null;
  }
}

export async function getEcosystemOrganizationNode(route = "/travel-guide") {
  const graph = await getEcosystemPageSchema(route);
  return (
    graph?.["@graph"].find((node) =>
      nodeTypes(node).some((type) => type === "Organization" || type === "TravelAgency" || type === "LocalBusiness"),
    ) ?? null
  );
}

export function graphNodesFromSchema(schema: Awaited<ReturnType<typeof getEcosystemPageSchema>>) {
  return schema?.["@graph"] ?? [];
}

function ecosystemContentRoot(): string {
  return (
    process.env.JVTO_EKOSYSTEM_CONTENT_ROOT ??
    path.resolve(process.cwd(), "..", "jvto-ekosistem")
  );
}

function reviewSchemaOutputRelativePath(id: number): string {
  return path.join(
    "5-experience-engine",
    "json-ld",
    "pages",
    `why-jvto__reviews__${id}.schema-output.json`,
  );
}

async function readLocalReviewSchema(
  id: number,
): Promise<{ "@context"?: string; "@graph": SchemaNode[] } | null> {
  try {
    const raw = await readFile(
      path.join(ecosystemContentRoot(), reviewSchemaOutputRelativePath(id)),
      "utf8",
    );
    const payload = JSON.parse(raw) as {
      json_ld?: { "@context"?: string; "@graph"?: unknown[] };
    };
    const graph = payload.json_ld;
    if (!graph || !Array.isArray(graph["@graph"])) return null;
    return graph as { "@context"?: string; "@graph": SchemaNode[] };
  } catch {
    return null;
  }
}

/**
 * Same local-file-first / HTTP-fallback pattern as ecosystemContent/website.ts's
 * getEcosystemWebsitePage — but for a DYNAMIC per-review route
 * (/why-jvto/reviews/{id}) that has no static list, so it can't rely on
 * getEcosystemPageSchema's single generic /api/schema/page reader alone without an
 * extra local-disk tier: the id count grows daily and this repo has no
 * page-by-page manifest of which review ids exist.
 *
 * Tier 1 — local dev shortcut: read the pre-rendered file straight off disk when no
 *   remote base URL is configured (JVTO_EKOSYSTEM_CONTENT_BASE_URL unset).
 * Tier 2 — remote ekosistem API (/api/schema/page?route=/why-jvto/reviews/{id}) —
 *   the real production source of truth. jvto-ekosistem's server.mjs
 *   (handleSchemaPage) resolves this route to the same
 *   why-jvto__reviews__{id}.schema-output.json file via its own routeToOutputBase,
 *   so no server-side change is needed on the ekosistem side for this to work.
 * Tier 3 — local fallback file (same path as tier 1) if the remote call fails.
 *
 * Returns null if none of the three tiers find the file. The caller decides what
 * "no schema" means for its route — see why-jvto/reviews/[id]/page.tsx, which calls
 * notFound() rather than soft-omitting the node, because a missing file here is
 * indistinguishable from "this id hasn't been generated by ekosistem yet" (accepted
 * risk, same class as booking-records).
 */
export async function getEcosystemReviewSchema(
  id: number,
): Promise<{ "@context"?: string; "@graph": SchemaNode[] } | null> {
  if (!process.env.JVTO_EKOSYSTEM_CONTENT_BASE_URL) {
    const local = await readLocalReviewSchema(id);
    if (local) return local;
  }

  const remote = await getEcosystemPageSchema(`/why-jvto/reviews/${id}`);
  if (remote) return remote;

  return readLocalReviewSchema(id);
}
