import { revalidatePath, revalidateTag } from "next/cache";
import { NextRequest, NextResponse } from "next/server";

type RevalidateRequestBody = {
  route?: string;
  routes?: string[];
};

const REVALIDATE_TAGS = [
  "jvto-ekosistem-content",
  "ecosystem-schema",
  "ecosystem-llms",
];

function normalizePath(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed.startsWith("/")) return null;
  if (trimmed.includes("://")) return null;
  return trimmed.length > 1 && trimmed.endsWith("/")
    ? trimmed.slice(0, -1)
    : trimmed;
}

function isAuthorized(request: NextRequest): boolean {
  const secret =
    process.env.ECOSYSTEM_REVALIDATE_SECRET ?? process.env.CRON_SECRET;
  if (!secret) return false;

  const auth = request.headers.get("authorization");
  return auth === `Bearer ${secret}`;
}

export async function POST(request: NextRequest) {
  if (!isAuthorized(request)) {
    return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
  }

  let body: RevalidateRequestBody = {};
  try {
    body = (await request.json()) as RevalidateRequestBody;
  } catch {
    body = {};
  }

  const requestedRoutes = [
    normalizePath(body.route),
    ...(Array.isArray(body.routes) ? body.routes.map(normalizePath) : []),
  ].filter((route): route is string => Boolean(route));

  const routes = Array.from(new Set([...requestedRoutes, "/llms.txt"]));

  for (const tag of REVALIDATE_TAGS) {
    revalidateTag(tag, "max");
  }
  for (const route of routes) {
    // Both forms, deliberately. revalidatePath(path) alone does not clear a
    // prerendered entry belonging to a dynamic segment generated by
    // generateStaticParams — which is how 11 crew pages stayed 404 on
    // 2026-08-21 after a transient upstream blip baked notFound() into the
    // cache: the route was in the revalidation set, was revalidated on every
    // ekosistem deploy, and never came back. Passing the "page" type is what
    // actually invalidates those entries.
    revalidatePath(route);
    revalidatePath(route, "page");
  }

  return NextResponse.json({
    ok: true,
    revalidated: {
      tags: REVALIDATE_TAGS,
      routes,
    },
  });
}
