import type { Metadata } from "next";
import { GoogleAnalytics } from '@/components/GoogleAnalytics' // <-- 1. Impor komponen

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Tambahkan komponen GA di sini */}
      {process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID && ( // <-- 2. Pastikan hanya berjalan jika ID ada
        <GoogleAnalytics />
      )}      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
