import { Suspense } from 'react'
import type { Metadata } from "next";
import { GoogleAnalytics } from '@/components/GoogleAnalytics' // <-- 1. Impor komponen
import { Poppins } from 'next/font/google';

import "./globals.css";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300','400','500','600','700','800','900'],  // atau sesuai kebutuhanmu
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Suspense>
          {/* {process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID && (
            <GoogleAnalytics />
          )} */}
                  <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght@200..700"
          rel="stylesheet"
        />
        </Suspense>
      </head>
      <body
        className={`${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
